DONETRADE = '/apiCustomer/reporting/doneTrade'
USERLOGIN = '/apiCustomer/accessRight/userLogin'
ACCOUNTINFO = '/apiCustomer/account/accountSummary' 
ADMININFO = '/apiTraderAdmin/accessRight/userLogin'
PRODINFO = '/apiTraderAdmin/product/productInfo'
CCYRATES = '/systemMaintance/systemOperation/getCcyRate'
CONTRACTSIZE = '/jLogin/product/downloadProductList'